name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Generate Dart code
        run: dart run build_runner build

      - name: Check Dart Code Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Dart Code
        run: dart analyze

      - name: Run Flutter Tests
        run: flutter test
